In [1]:
print('hi')

Error: Jupyter cannot be started. Error attempting to locate jupyter: 'Kernelspec' module not installed in the selected interpreter (C:\Users\nitis\anaconda3\envs\pyt-drl\python.exe).
 Please re-install or update 'jupyter'.

In [10]:
import numpy as np

In [3]:
from collections import namedtuple

nt = namedtuple('Test', field_names=[
    "field1",
    "field2"
])


In [5]:
test1 = nt(1,2)

In [15]:
np.random.choice(5, 2)

array([1, 1])

In [16]:
states = [[1,1,1], [2,2,2]]
actions[1,2,3]
rewards = [1,1,0]
dones=[0,0,1]
next_states = [[2,2,2], [2,2,3]]



NameError: name 'actions' is not defined

In [17]:
np.random.random()

0.1632422309379733

In [1]:
import torch
a, b=torch.tensor([1,2,3,4], dtype=torch.float32), torch.tensor([3,4,5])

In [78]:
torch.argmax(a)

tensor(2)

In [31]:
b = a.detach().clone()

In [34]:
b[2]=23

In [35]:
b

tensor([ 1.,  2., 23.,  4.])

In [36]:
a

tensor([1., 2., 3., 4.])

In [74]:
a = torch.rand(size = (5, 2))
a

tensor([[0.6346, 0.2365],
        [0.9638, 0.7175],
        [0.8118, 0.8216],
        [0.5719, 0.5431],
        [0.5103, 0.2338]])

In [75]:
ind = np.array([1,2])

In [76]:
a[ind,[1,0]] = 0

In [77]:
a

tensor([[0.6346, 0.2365],
        [0.9638, 0.0000],
        [0.0000, 0.8216],
        [0.5719, 0.5431],
        [0.5103, 0.2338]])

In [60]:
actions = torch.randint(0,2, size=(2,))

In [61]:
actions

tensor([1, 0])

In [62]:
indices = torch.tensor([1,2])

a[indices][actions]

tensor([[0.0666, 0.2361],
        [0.7489, 0.6716]])

In [4]:
A = torch.IntTensor([True, True, False])

In [5]:
A

tensor([1, 1, 0], dtype=torch.int32)

In [7]:
B= torch.FloatTensor([1,2,3])

In [8]:
(1-A)*B

tensor([0., 0., 3.])

In [9]:
A.shape

torch.Size([3])

In [10]:
b.shape

torch.Size([3])